a=int(input("introdu numarul de oua facute de gaina 1 in prima zi: "))
b=int(input("introdu numarul de oua facute de gaina 2 in prima zi: "))
c=int(input("introdu numarul de oua facute de gaina 3 in prima zi: "))
d=int(input("introdu numarul de oua facute de gaina 4 in prima zi: "))
z1=a+b+c+d
a=int(input("introdu numarul de oua facute de gaina 1 in a doua zi: "))
b=int(input("introdu numarul de oua facute de gaina 2 in a doua zi: "))
c=int(input("introdu numarul de oua facute de gaina 3 in a doua zi: "))
d=int(input("introdu numarul de oua facute de gaina 4 in a doua zi: "))
z2=a+b+c+d
a=int(input("introdu numarul de oua facute de gaina 1 in a treia zi: "))
b=int(input("introdu numarul de oua facute de gaina 2 in a treia zi: "))
c=int(input("introdu numarul de oua facute de gaina 3 in a treia zi: "))
d=int(input("introdu numarul de oua facute de gaina 4 in a treia zi: "))
z3=a+b+c+d
a=int(input("introdu numarul de oua facute de gaina 1 in a patra zi: "))
b=int(input("introdu numarul de oua facute de gaina 2 in a patra zi: "))
c=int(input("introdu numarul de oua facute de gaina 3 in a patra zi: "))
d=int(input("introdu numarul de oua facute de gaina 4 in a patra zi: "))
z4=a+b+c+d
a=int(input("introdu numarul de oua facute de gaina 1 in a cincea zi: "))
b=int(input("introdu numarul de oua facute de gaina 2 in a cincea zi: "))
c=int(input("introdu numarul de oua facute de gaina 3 in a cincea zi: "))
d=int(input("introdu numarul de oua facute de gaina 4 in a cincea zi: "))
z5=a+b+c+d
a=int(input("introdu numarul de oua facute de gaina 1 in a sasea zi: "))
b=int(input("introdu numarul de oua facute de gaina 2 in a sasea zi: "))
c=int(input("introdu numarul de oua facute de gaina 3 in a sasea zi: "))
d=int(input("introdu numarul de oua facute de gaina 4 in a sasea zi: "))
z6=a+b+c+d
a=int(input("introdu numarul de oua facute de gaina 1 in a saptea zi: "))
b=int(input("introdu numarul de oua facute de gaina 2 in a saptea zi: "))
c=int(input("introdu numarul de oua facute de gaina 3 in a saptea zi: "))
d=int(input("introdu numarul de oua facute de gaina 4 in a saptea zi: "))
z7=a+b+c+d
print ("gainele au facut",z1+z2+z3+z4+z5+z6+z7,"oua intro saptamana")
